name: C/C++ CI for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Usa l'ultima versione disponibile di Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install

    - name: Install dependencies with vcpkg
      run: |
        .\vcpkg\vcpkg install fmt:x64-windows
        .\vcpkg\vcpkg install llvm:x64-windows
        .\vcpkg\vcpkg install triton:x64-windows
        .\vcpkg\vcpkg install range-v3:x64-windows

    - name: Configure CMake with vcpkg toolchain
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/*.*  

