name: C/C++ CI for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest  # Utilizza l'ultima versione disponibile di Windows

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up CMake
      uses: lukka/get-cmake@latest  # Assicura di usare l'ultima versione di CMake

    - name: Create Build Environment
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest -C Release -R TestPattern --output-on-failure
      working-directory: build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/*.exe
