name: C/C++ CI for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 180

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ninja
      run: choco install ninja

    - name: Cache vcpkg libraries
      id: cache-vcpkg
      uses: actions/cache@v3
      with:
        path: |
          D:/a/_work/titan-1/titan-1/vcpkg/installed
          !D:/a/_work/titan-1/titan-1/vcpkg/packages
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install vcpkg if not cached
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
        .\vcpkg\vcpkg integrate install

    - name: Install Python with vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: .\vcpkg\vcpkg install python3:x64-windows --debug

    - name: Install fmt with vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: .\vcpkg\vcpkg install fmt:x64-windows --debug

    - name: Install llvm with vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: .\vcpkg\vcpkg install llvm:x64-windows --debug

    - name: Install triton with vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: .\vcpkg\vcpkg install triton:x64-windows --debug

    - name: Install range-v3 with vcpkg
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: .\vcpkg\vcpkg install range-v3:x64-windows --debug

    - name: Configure CMake with vcpkg toolchain using Ninja
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build with Ninja
      run: |
        cmake --build build --config Release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/*.*
